name: Android CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request: 
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Riru modules
        run: ls riru/Riru-ModuleTemplate
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_STORE_BASE64 }}
        run: echo $ENCODED_STRING | base64 -di > app/keystore.jks
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Build Riru modules
        run: cd ./riru && bash ./make.sh
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean ":app:assembleRelease"
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload Apk
        uses: actions/upload-artifact@v2.2.0
        with:
          name: fingerprintPay.xposed.${{ steps.current-time.outputs.formattedTime }}
          path: app/build/outputs/apk/release/*.apk
      - name: Upload Riru Modules
        uses: actions/upload-artifact@v2.2.0
        with:
          name: fingerprintPay.magisk.${{ steps.current-time.outputs.formattedTime }}
          path: |
            riru/build/release/*.zip
            !riru/build/release/*-all-*.zip
